# Generated by Django 3.2 on 2023-04-25 09:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='publication_date')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='GenreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=1, error_messages={'validators': 'Rating from 1 to 10!'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='rating')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='publication date')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'review',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'title',
                'verbose_name_plural': 'title',
                'ordering': ('year',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('genrecategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.genrecategory')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'category',
            },
            bases=('reviews.genrecategory',),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genrecategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reviews.genrecategory')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genre',
            },
            bases=('reviews.genrecategory',),
        ),
    ]
